### PR TITLE
chore: remove security API ReadFile/WriteFile

### PR DESCRIPTION
**Pull request by smira**
This seems to be unused completely, and they look scary enough at the
same time.

For better readability and to avoid any pitfalls, better to remove them.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]
We should back port this to 0.9?

**Comment by smira** [comment]
> We should back port this to 0.9?

I don't see exact reason to backport? these APIs haven't been used for quite some time. or are you thinking about security risk?

**Comment by andrewrynhard** [comment]
> > We should back port this to 0.9?
> 
> I don't see exact reason to backport? these APIs haven't been used for quite some time. or are you thinking about security risk?

Yep, exactly. Just to feel better about things.

**Pull request merged**
