### PR TITLE
release(v0.13.5): prepare release

### PR DESCRIPTION
**Pull request by smira**
This is the official v0.13.5 release.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4839)

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
e2e-misc failed because of Canal test which we have disabled in >= 0.14 (as Calico ships now with binaries linked to glibc):

image

Ignoring this faiure

**Pull request merged**
