### PR TITLE
Added documentation for creating cluster on Hyper-V

### PR DESCRIPTION
**Pull request by nebula-it**
# Pull Request

## What? (description)
Added documentation for setting up Talos cluster on Hyper-V. 

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [x] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4818)

### CODE REVIEW

**Comment by smira** [comment]
@nebula-it thanks for the PR, would you mind fixing the conformance issues on the commit itself?

`make conformance` should show the issues locally, you can ignore the GPG errors, but we need DCO (`git ci --amend -s`) and proper conventional commit format (https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by nebula-it** [comment]
@smira Looks good now?

**Comment by rsmitty** [comment]
reworked just a bit. should be good to go now. thx so much for the contribution!

**Review by rsmitty — APPROVED** [review]

**Pull request merged**
