### PR TITLE
fix: vmware documentation typo

### PR DESCRIPTION
**Pull request by ShaharNaveh**
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4792)

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]
/ok-to-test

**Comment by smira** [comment]
@ShaharNaveh thanks for the PR, would you mind fixing the DCO in the commit?

Please don't worry about GPG signature, we will fix it up later.

**Review by smira — APPROVED** [review]

**Pull request merged**
