### PR TITLE
test: bump AWS and GCP tests to use CAPI v1beta1

### PR DESCRIPTION
**Pull request by Unix4ever**
Both AWS and GCP should support that.

Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4616)

### CODE REVIEW

**Comment by smira** [comment]
@Unix4ever I believe this can be closed, as @rsmitty has this already updated

**Comment by Unix4ever** [comment]
Yep, correct

**Pull request closed without merging**
