### PR TITLE
fix: update go-blockdevice to fix disk type detection

### PR DESCRIPTION
**Pull request by Unix4ever**
Otherwise it never detected mmc and nvme devices as such.

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>

### CODE REVIEW

**Review by smira — COMMENTED** [review]
Looking at the diff, do we need to update same for pkg/machinery/go.mod

**Comment by Unix4ever** [comment]
> Looking at the diff, do we need to update same for pkg/machinery/go.mod

Done!

**Comment by smira** [comment]
My guess it can be go mod tidied now ) start with machinery and move to the top level :)

**Pull request merged**
