### PR TITLE
docs: add cilium guide

### LINKED ISSUE #4477: Outdated cilium install instructions
The documentation of Talos v.0.13.1 states:
```
# # The CNI used.
# cni:
#     name: custom # Name of CNI to use.
#     # URLs containing manifests to apply for the CNI.
#     urls:
#         - https://raw.githubusercontent.com/cilium/cilium/v1.8/install/kubernetes/quick-install.yaml
```
However, the quick-install.yaml option for cilium is no longer available since cilium v1.10.

### PR DESCRIPTION
**Pull request by frezbo**
- Add Cilium CNI install guide
- Use Canal CNI for default examples

Fixes #4477

Signed-off-by: Noel Georgi <git@frezbo.dev>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4698)

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by xmulligan** [comment]
@frezbo Thanks for adding support for Cilium as a CNI! 🚀 would you mind adding Talos to the Cilium adopters list? https://github.com/cilium/cilium/blob/master/USERS.md

We need this for when we apply to graduate at the CNCF

**Comment by frezbo** [comment]
@xmulligan https://github.com/cilium/cilium/pull/18879

**Comment by xmulligan** [comment]
@frezbo Thanks for the addition! If you want some Cilium stickers, DM your address on Twitter and I can get them sent to you :)

**Pull request merged**
