### PR TITLE
refactor: bring more control to install.Manifest execution

### PR DESCRIPTION
**Pull request by smira**
This unifies more code paths under the control of `install.Manifest` vs.
being split across the installer and manifest code.

There should be no functional changes now.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — DISMISSED** [review]
I know preserve is broken, but just to be clear we will be adding something back in in another PR to enable it again?

**Review by andrewrynhard — APPROVED** [review]

**Comment by smira** [comment]
> I know preserve is broken, but just to be clear we will be adding something back in in another PR to enable it again?

Yes, exactly, for now I added a check to deny !force upgrades early

**Pull request merged**
