### PR TITLE
feat: add ULA prefix for SideroLink

### PR DESCRIPTION
**Pull request by smira**
Allocate one more value for the SideroLink feature.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4559)

### CODE REVIEW

**Comment by Ulexus** [comment]
Do we have any Sidero installation-unique ID we can use for the cluster ID?  It's important for ULA to actually _be_ unique.

**Comment by smira** [comment]
> Do we have any Sidero installation-unique ID we can use for the cluster ID? It's important for ULA to actually _be_ unique.

my only concern with that is that someone reinstalls Sidero, they might lose it.. I wish we had a way to do good persistence, but we can get back to this. We need anyway to persist Sidero Wireguard key.

So the scenario I'm thinking about: I have a bunch of servers, and I want to upgrade Sidero. I want to make sure SideroLink is not interrupted by the upgrade, so that nodes can reconnect back.

**Comment by smira** [comment]
I added some preparation to provide site-specific SideroLink ULA addresses.

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
