### PR TITLE
chore: bump dependencies via dependabot

### PR DESCRIPTION
**Pull request by smira**
Fixes #3993 #3994 #3995

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by AlekSi** [comment]
```
/src/pkg/cluster/sonobuoy/sonobuoy.go:190:11: runConfig.E2EConfig undefined (type *"github.com/vmware-tanzu/sonobuoy/pkg/client".RunConfig has no field or method E2EConfig)
```

**Comment by smira** [comment]
> ```
> /src/pkg/cluster/sonobuoy/sonobuoy.go:190:11:
> runConfig.E2EConfig undefined
> (type *"github.com/vmware-tanzu/sonobuoy/pkg/client".RunConfig has no field or method E2EConfig)
> ```

yep, I'll get that fixed in a minute

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
