### PR TITLE
feat: add /system directory

### PR DESCRIPTION
**Pull request by andrewrynhard**
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2253)

### CODE REVIEW

**Comment by andrewrynhard** [comment]
I don't know why just yet, but I am seeing:

```
2020/07/01 04:00:27 service[networkd](Running): Health check failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /system/run/networkd/networkd.sock: connect: no such file or directory"
```

**Comment by alex1989hu** [comment]
It solves the Cilium issue 👍

**Pull request merged**
