### PR TITLE
feat: ignore bootstrap API request if cluster is already bootstrapped

### PR DESCRIPTION
**Pull request by smira**
This refactors some initialized checks into common etcd client code and
adds a check to the bootstrap API.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by andrewrynhard** [comment]
We thinking we don't need this anymore?

**Comment by smira** [comment]
> We thinking we don't need this anymore?

I decided to close that as it doesn't quite work with API timeouts and causes frequent failures, probably in the new sequencer it will be much easier to implement it some other way.

**Pull request closed without merging**
