### PR TITLE
chore: add drone pipeline to upload cloud images

### PR DESCRIPTION
**Pull request by smira**
At the moment only AMIs for AWS, and upload results should be pushed
back to the docs as separate PR.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
sample run https://ci.dev.talos-systems.io/talos-systems/talos/13816/1/22

**Review by andrewrynhard — APPROVED** [review]

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
