### PR TITLE
fix: backport fixes from 0.9 after 0.8-beta.0

### LINKED ISSUE #2974: upgrade fails with Calico on master nodes
failure to remove pod - interaction with CNI

```
[  334.009087] [talos] upgrade failed: error running phase 3 in upgrade sequence: task 1/1: failed, failed stopping pod kube-system/kube-scheduler-8cmf4: StopPodSandbox "98933c08971c545952da69feafb744e6d575faa2e5a571a43776836eed12a03d" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "98933c08971c545952da69feafb744e6d575faa2e5a571a43776836eed12a03d": Get "https://[192.168.128.1]:443/apis/crd.projectcalico.org/v1/ipamhandles/k8s-pod-network.98933c08971c545952da69feafb744e6d575faa2e5a571a43776836eed12a03d": stream error: stream ID 1; INTERNAL_ERROR
[  334.061766] [talos] fatal sequencer error in "upgrade" sequence: message:"sequence failed: error running phase 3 in upgrade sequence: task 1/1: failed, failed stopping pod kube-system/kube-scheduler-8cmf4: StopPodSandbox \"98933c08971c545952da69feafb744e6d575faa2e5a571a43776836eed12a03d\" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox \"98933c08971c545952da69feafb744e6d575faa2e5a571a43776836eed12a03d\": Get \"https://[192.168.128.1]:443/apis/crd.projectcalico.org/v1/ipamhandles/k8s-pod-network.98933c08971c545952da69feafb744e6d575faa2e5a571a43776836eed12a03d\": stream error: stream ID 1; INTERNAL_ERROR"
{"level":"warn","ts":"2020-12-21T17:21:49.932Z","caller":"clientv3/retry_interce[  334.125730] [talos] rebooting in 10 seconds
ptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-3edf2a4f-029b-4177-8fc7-bc489cbeb158/10.100.2.15:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
```

```
[269047.779689] [talos] removing container kube-system/kube-scheduler-8cmf4:kube-scheduler
[269047.788143] [talos] removing container kube-system/kube-controller-manager-ps75s:kube-controller-manager
[269047.798477] [talos] removing container kube-system/kube-controller-manager-ps75s:kube-controller-manager
[269047.809431] [talos] removed container kube-system/kube-scheduler-8cmf4:kube-scheduler
[269047.822862] [talos] removed container kube-system/kube-controller-manager-ps75s:kube-controller-manager
[269047.940219] [talos] removed container kube-system/kube-scheduler-8cmf4:kube-scheduler
[269048.001543] [talos] removed container kube-system/kube-controller-manager-ps75s:kube-controller-manager
[269048.760968] [talos] removed pod kube-system/kube-scheduler-8cmf4
[269048.796777] tipc: TX() has been purged, node left!
[269108.695983] [talos] task removeAllPods (1/1): failed
[269108.701296] [talos] task removeAllPods (1/1): done, 1m1.112636769s
[269108.707716] [talos] phase cleanup (3/11): failed
[269108.712548] [talos] upgrade sequence: failed
[269108.717024] [talos] upgrade sequence: done: 1m25.541992103s
[269108.722825] [talos] upgrade failed: error running phase 3 in upgrade sequence: task 1/1: failed, failed stopping pod kube-system/kube-controller-manager-ps75s: StopPodSandbox "7fefefacd405e52a2c4c8b3e0a71473e2ee39dc49f1dc84c8d79e466e604e5a6" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "7fefefacd405e52a2c4c8b3e0a71473e2ee39dc49f1dc84c8d79e466e604e5a6": the server was unable to return a response in the time allotted, but may still be processing the request (get IPAMHandles.crd.projectcalico.org k8s-pod-network.7fefefacd405e52a2c4c8b3e0a71473e2ee39dc49f1dc84c8d79e466e604e5a6)
[269108.778873] [talos] fatal sequencer error in "upgrade" sequence: message:"sequence failed: error running phase 3 in upgrade sequence: task 1/1: failed, failed stopping pod kube-system/kube-controller-manager-ps75s: StopPodSandbox \"7fefefacd405e52a2c4c8b3e0a71473e2ee39dc49f1dc84c8d79e466e604e5a6\" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox \"7fefefacd405e52a2c4c8b3e0a71473e2ee39dc49f1dc84c8d79e466e604e5a6\": the server was unable to return a response in the time allotted, but may still be processing the request (get IPAMHandles.crd.projectcalico.org k8s-pod-network.7fefefacd405e52a2c4c8b3e0a71473e2ee39dc49f1dc84c8d79e466e604e5a6)"
```

### PR DESCRIPTION
**Pull request by smira**
PRs backported: #2989, #2967, #2982, #2976, #2979, #2965, #2983, #2984,
                #2971, #2988, #2986, #2990

fix: don't run LabelNodeAsMaster in two sequences

It was run both as part of `Boot` and `Bootstrap` sequences, remove it
from the `Bootstrap` sequence.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
(cherry picked from commit e791e7dca95175671e058c9cc72e280b681b7bc1)

fix: ignore errors on stopping/removing pod sandboxes

Talos stops CRI pods and containers before upgrade to make sure
ephemeral partition is not mounted anymore. At the same time with
different CNIs it's frequent that removing stop sandbox might fail
because of CNI teardown issue (dependency on API server being up, for
example). As upgrade only depends on volume mounts and doesn't require
CNI to be stopped, we can ignore such errors.

Plus installer anyway does mount check across all mount namespaces, so
it will abort if ephemeral partition is still mounted.

Fixes #2974

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
(cherry picked from commit f1964aab5314f9d8e1106f68611aec666463dd30)

fix: leave etcd for staged upgrades

Upgrade itself is going to happen after the reboot, but we need to leave
etcd if the disks are to be wiped (!preserve) upgrade.

We're not doing integration test right now, as we need source version
for the upgrade to contain a fix. We can add a test once we release new
version with this fix (dropped a note to look into that later).

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
(cherry picked from commit e75bb27cf4c3a828ac8a6e70603257dc075a49be)

fix: use the correct console on Banana Pi M64

This updates the `console` arg for the `bananapi_m64` board to the correct value.

Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
(cherry picked from commit 941556cffbcadcb4c3334d0da30c4e9077e91ab5)

feat: update Kubernetes to 1.20.1

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
(cherry picked from commit b1d4814308dd35d75b5c3a93f73f6faa0a673d77)

fix: ignore pods spun up from checkpoints in health checks

Pods which are spun up as checkpoints shouldn't be counted towards the
normal pods spun up as part of the daemon set.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
(cherry picked from commit 5e3b8ee099f8b3d2d2d37e507b7eb3a064894cd7)

fix: use SetAll instead of AppendAll when building kernel args

SBC should always overwrite default kernel params.
Otherwise we will always get duplicate values for some of them.

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>
(cherry picked from commit 47fb7d26e0a2887a524802788523ec5ff9ad3af6)

fix: add more dependencies for bootstrap services

CRI now waits for etcd to be up on control plane nodes, this makes sure
that if CRI is going to start kube-apiserver, API server will be able to
connect to local etcd.

Bootkube waits for kubelet to be healthy, as bootkube relies on kubelet
to start its operations.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
(cherry picked from commit b4ddfbfe9bec8d4fc7e8e68a112b62e583860f23)

feat: support disk image in talosctl cluster create

Fixes: https://github.com/talos-systems/talos/issues/2973

Can now supply disk image using `--disk-image-path` flag.
May need to enable `--with-apply-config` if it's necessary to bootstrap
nodes properly.

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>
(cherry picked from commit 6540e9bf70d5682ebe67682cd865b30a156f0665)

fix: pass disk image flags to e2e-qemu cluster create command

Forgot to add it in the original PR.

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>
(cherry picked from commit 73c81c501e239f06df23731df21d53125f570fa7)

feat: add commands to manage/query etcd cluster

Used already existing protobufs for that.

Commands:
`talosctl etcd members -n <node>`
`talosctl etcd leave -n <node>`
`talosctl etcd forfeit-leadership -n <node>`

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>
(cherry picked from commit a83e8758db66e1b45e69b888d9240ff94fb85c7f)

fix: correctly transport gRPC errors from apid

Before these changes, errors were always sent as strings, so if original
error was gRPC error (which is almost always the case for apid), it is
formatted as string and original fields (like code) are lost in the
formatted string.

With this change, apid sends errors as official `grpc.Status` protobuf
structure, and client decodes that into Go grpc.Status based error.

This change is backwards and forwards compatible.

This should fix more cases when integration tests were not able to
ignore grpc `transport is closing` errors when they were sent as strings
from the apid endpoint.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
(cherry picked from commit 6a0e652f0c0ca7ccee58b8e7eaf5c0553963a201)

### CODE REVIEW

**Review by rsmitty — APPROVED** [review]

**Comment by smira** [comment]
e2e-aws passed https://ci.dev.talos-systems.io/talos-systems/talos/14041/1/23

**Comment by smira** [comment]
integration passed: https://ci.dev.talos-systems.io/talos-systems/talos/14040

**Pull request merged**
