### PR TITLE
fix: do not format state partition in the initialize sequence

### PR DESCRIPTION
**Pull request by Unix4ever**
Initialize state should be only reading the config.
So now if it detects that the partition is not even formatted it will
skip it and will consider the state to be empty.

Fixes: https://github.com/talos-systems/talos/issues/3759

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/3769)

### CODE REVIEW

**Comment by smira** [comment]
Should we start testing this flow now, e.g. in `e2e-disk-image` we could enable encryption (or add another one with disk-image + encryption)?

**Comment by Unix4ever** [comment]
yep, can do that.

**Review by smira — APPROVED** [review]

**Review by smira — APPROVED** [review]

**Pull request merged**
