### PR TITLE
chore: use vtprotobuf compiled marshaling in Talos API

### PR DESCRIPTION
**Pull request by AlekSi**
Use `vtprobuf` optimized Marshal/Unmarshal methods which do not depend
on reflection to reduce memory and CPU usage while using Talos API.

See https://github.com/planetscale/vtprotobuf and
https://vitess.io/blog/2021-06-03-a-new-protobuf-generator-for-go/

### CODE REVIEW

**Review by Unix4ever — APPROVED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Review by smira — APPROVED** [review]
:cool:

**Pull request merged**
