### PR TITLE
fix: update DHCP client to use Request-Ack sequence after an Offer

### PR DESCRIPTION
**Pull request by smira**
The problem was that our DHCP client was always doing
Discover-Offer-Request-Ack sequence as if it doesn't have any IP lease
which was breaking some DHCP servers leading to an error which in turn
makes Talos retry harder hitting the same error over and over again.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
thinking more about it, we should probably clear an offer only once TTL runs out?

**Comment by smira** [comment]
> thinking more about it, we should probably clear an offer only once TTL runs out?

I couldn't find any better strategy than clearing an offfer on error

**Review by Ulexus — APPROVED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
