### PR TITLE
fix: correctly transport gRPC errors from apid

### PR DESCRIPTION
**Pull request by smira**
Before these changes, errors were always sent as strings, so if original
error was gRPC error (which is almost always the case for apid), it is
formatted as string and original fields (like code) are lost in the
formatted string.

With this change, apid sends errors as official `grpc.Status` protobuf
structure, and client decodes that into Go grpc.Status based error.

This change is backwards and forwards compatible.

This should fix more cases when integration tests were not able to
ignore grpc `transport is closing` errors when they were sent as strings
from the apid endpoint.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by Unix4ever — DISMISSED** [review]

**Review by Unix4ever — APPROVED** [review]

**Review by Unix4ever — APPROVED** [review]

**Comment by smira** [comment]
clean integration run: https://ci.dev.talos-systems.io/talos-systems/talos/14031

**Pull request merged**
