### PR TITLE
docs: add fallback to default description if none is set on current page

### PR DESCRIPTION
**Pull request by Unix4ever**
Also filled in some of the descriptions specific for particular pages.
Seeing that bug all the time was making me sad:
image

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>

### CODE REVIEW

**Review by smira — DISMISSED** [review]
this `undefined` was bugging me as well

**Review by rsmitty — DISMISSED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
