### PR TITLE
chore: remove deprecated "join" term

### LINKED ISSUE #3910: Deprecated things to remove in 0.13
* [x] `talosctl`'s `--config-patch-join` flag (it is `--config-patch-worker` since v0.12).
* [x] `WithJSONPatchJoin` in `pkg/machinery/config/types/v1alpha1/bundle`.
* [x] `ConfigBundle.Join` in `pkg/machinery/config/types/v1alpha1`.
* [x] `TypeJoin` in `pkg/machinery/config/types/v1alpha1/machine` (and a lot of `//nolint:exhaustive` as result).

### PR DESCRIPTION
**Pull request by AlekSi**
Closes #3910.

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4293)

### CODE REVIEW

**Review by smira — APPROVED** [review]
my only feat is that don't break any existing machine config with `join` type on upgrade. I know we shouldn't, but still

**Comment by AlekSi** [comment]
That should be covered by https://github.com/talos-systems/talos/blob/0e18e2800fc038a86ed2fd9b042278ae29070bb5/pkg/machinery/config/types/v1alpha1/machine/machine.go#L46-L47

**Comment by AlekSi** [comment]
Re-added a tiny test to ensure compatibility

**Review by smira — APPROVED** [review]

**Pull request merged**
