### PR TITLE
fix: improve error message on empty config

### LINKED ISSUE #2096: talosctl: Missing context
### Description

When running a `talosctl` command without `~/.talos/config` existing, we create it and then fail complaining that there is no context.

I feel like we should fail on missing talos config file.

### Logs

```
error getting client credentials: 'context' key is not set in the config
```

### PR DESCRIPTION
**Pull request by smira**
Fixes #2096

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2534)

### CODE REVIEW

**Comment by smira** [comment]
with the fix:

```sh
$ talosctl list
error constructing client: failed to resolve configuration context: talos config file is empty
```

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
