### PR TITLE
test: attempt number on two on proper retries in CLI time tests

### PR DESCRIPTION
**Pull request by smira**
See #4702

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4718)

### CODE REVIEW

**Comment by smira** [comment]
The issue was that `*.cmd.Cmd` can't be executed multiple times - only once, so if we need to retry, we need to build new `*cmd.Cmd`

**Review by Unix4ever — APPROVED** [review]

**Review by Ulexus — APPROVED** [review]

**Pull request merged**
