### PR TITLE
release(v1.0.0-beta.0): prepare release

### PR DESCRIPTION
**Pull request by smira**
This is the official v1.0.0-beta.0 release.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/5083)

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]
🎉

**Review by frezbo — APPROVED** [review]
:heart_eyes:

**Pull request merged**
