### PR TITLE
docs: improve the config reference documentation

### PR DESCRIPTION
**Pull request by smira**
Lots of small changes, changing layout, adding back references,
propagating examples, etc.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
https://5f9b2e9f44883e0007b08f14--talos-dev.netlify.app/docs/v0.7/reference/configuration/

**Comment by smira** [comment]
https://deploy-preview-2701--talos-dev.netlify.app/docs/v0.7/reference/configuration/

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
