### PR TITLE
feat: extract config generation

### PR DESCRIPTION
**Pull request by borancar**
Extract config generation into a seperate function. This reduces
cyclomatic complexity with the added benefit of being able to use
generation in another tool (e.g. Terraform provider to generate config).

Signed-off-by: Boran Car <boran.car@gmail.com>

# Pull Request

## What? (description)

Extract the config bundle generation into a separate function that can be invoked externally.

## Why? (reasoning)

Primarily this is to enable creating a terraform provider so that talos generation can be easily rolled into typical terraform flows, without needing to stage it. The added benefit here is that it also reduces cyclomatic complexity of the original function. Still not enough though to remove the linting exception (cyclo is now at 15, whereas needs to be under 10).

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [x] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by andrewrynhard** [comment]
Great idea. Thanks @borancar !

**Review by smira — APPROVED** [review]
lgtm for the refactoring!

I thought if we should move `GenV1alpha1Config` function to machinery package to improve usability from other tools (as `pkg/machinery` is the public importable sub-module)

**Comment by borancar** [comment]
> I thought if we should move GenV1alpha1Config function to machinery package to improve usability from other tools (as pkg/machinery is the public importable sub-module)

I'm game either. Any point in also refactoring the parameters into GenOptions then? Well, at least some of them like the JSON patch overrides?

**Comment by smira** [comment]
discussed during the meeting: we're going to merge this PR and keep iterating on the approach:

* move into `pkg/machinery`
* clean up input arguments moving more to `GenOptions`, etc.

**Pull request merged**
