### PR TITLE
feat: inject platform network configuration as network resources

### PR DESCRIPTION
**Pull request by smira**
Instead of patching in the machine config, provide a new interface in
the platforms to supply platform-specific network configuration.

Configuration will be cached in the `/state` across reboots, and
configuration might be even updated in real time (e.g. on GCP).

Network configuration on platform level can be overridden with
user-supplied machine configuration.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4755)

### CODE REVIEW

**Comment by smira** [comment]
TODO:

- [ ] more tests from platform_config.go
- [ ] nocloud
- [ ] openstack
- [ ] scaleway
- [ ] upcloud
- [ ] vultr
- [ ] merge oraclecloud
- [ ] oraclecloud

**Comment by smira** [comment]
testing:

- [ ] AWS
- [x] GCP
- [x] Metal
- [x] Equinix Metal
- [ ] Oracle Cloud
- [ ] Digital Ocean
- [ ] Azure
- [ ] OpenStack

**Review by frezbo — APPROVED** [review]

**Review by Ulexus — CHANGES_REQUESTED** [review]
> Reviewed 49 of 67 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4755)* status: 49 of 67 files reviewed, 9 unresolved discussions (waiting on @smira and @Ulexus)

___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 82 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthbwoP2JXSP9U4vpIX:-MthbwoP2JXSP9U4vpIY:b-32ja2a) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L82)):*
> ```Go
> 			existing, ok := operators[id]
> 			if ok && existing.TypedSpec().ConfigLayer > operator.TypedSpec().ConfigLayer {
> 				// skip this address, as existing one is higher layer
> ```

s/address/operator/ ?
___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 103 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthcGhc9vnQuPNTzCQA:-MthcGhc9vnQuPNTzCQB:b3nk22m) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L103)):*
> ```Go
> 				if state.IsPhaseConflictError(err) {
> 					// phase conflict, resource is being torn down, skip updating it and trigger reconcile
> 					// later by failing the
> ```

by failing the ... ?
___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 113 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthcSS-1nLNaZ5GO61R:-MthcSS-1nLNaZ5GO61S:b-f2h3ki) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L113)):*
> ```Go
> 		}
> 
> 		// list addresses for cleanup
> ```

s/addresses/operators/
___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 125 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthcWQp5dOjvcfUC0Zj:-MthcWQp5dOjvcfUC0Zk:bcznuga) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L125)):*
> ```Go
> 				okToDestroy, err = r.Teardown(ctx, res.Metadata())
> 				if err != nil {
> 					return fmt.Errorf("error cleaning up addresses: %w", err)
> ```

operators
___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 130 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthcYVI3eAOIBWfJ1LK:-MthcYVI3eAOIBWfJ1LL:bcznuga) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L130)):*
> ```Go
> 				if okToDestroy {
> 					if err = r.Destroy(ctx, res.Metadata()); err != nil {
> 						return fmt.Errorf("error cleaning up addresses: %w", err)
> ```

operators
___
*[internal/app/machined/pkg/controllers/network/platform_config.go, line 102 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthdJVj8V9q8VNkqMAe:-MthdJVj8V9q8VNkqMAf:b-f02c8a) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/platform_config.go#L102)):*
> ```Go
> func (ctrl *PlatformConfigController) Run(ctx context.Context, r controller.Runtime, logger *zap.Logger) error {
> 	if ctrl.StatePath == "" {
> 		ctrl.StatePath = constants.StateMountPoint
> ```

This seems like a weird place for asserting an unrelated constant.  Is the controller not fully instantiated here?  If this is truly a constant which is not affected by anything else, should this go in the controller instantiation instead?
___
*[internal/app/machined/pkg/controllers/network/platform_config.go, line 184 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthqCcJEmdbNqmRznD7:-MthpcRNDQQkpqRso9-a:b-21frmr) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/platform_config.go#L184)):*
> ```Go
> 
> 		switch {
> 		// prefer live network config over cached config always
> ```

Could this prioritisation just be handled by a config layer for caching... with a sufficiently broad resource type to force conflict?
___
*[internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go, line 180 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-Mti-TxfEfo7FwWhkR4w:-Mti-TxfEfo7FwWhkR4x:bt6ilwo) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go#L180)):*
> ```Go
> 
> 				if family == nethelpers.FamilyInet6 {
> 					route.Priority = 2048
> ```

AFAIK, IPv6 default routes' default metric is 1024.  I don't know what we're using elsewhere, but a route metric of 2048 is likely to be clobbered, if defaults are otherwise similar.
___
*[internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go, line 247 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-Mti45AB6N_BIJOkBUvX:-Mti45ACDmTk2IwCyoVx:b2okx77) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go#L247)):*
> ```Go
> 
> 			if addr.Family == 6 {
> 				route.Priority = 2 * networkctrl.DefaultRouteMetric
> ```

I see that this is just copied from the previous implementation, but I don't understand the purpose.  Route metrics between IPv4 and IPv6 are meaningless; they will never be compared.  So why is this doubling the default route metric here?

**Review by Ulexus — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4755)* status: 49 of 67 files reviewed, 10 unresolved discussions (waiting on @smira and @Ulexus)

*[a discussion](https://reviewable.io/reviews/talos-systems/talos/4755#-Mti50Q20nqHVpyfHZ10:-Mti50Q20nqHVpyfHZ11:brm3qj4) (no related file):*
This network config caching system feels like something which should have both more generalisation and more conformance.  It doesn't feel correct to tie it to the platform operators, and it could conceptually apply to other configuration aspects.  It's also making the platform operator code about three times the complexity it would otherwise seem to need.

Maybe it's out of scope for this PR

---

**Review by smira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4755)* status: 49 of 67 files reviewed, 10 unresolved discussions (waiting on @Ulexus)

*[a discussion](https://reviewable.io/reviews/talos-systems/talos/4755#-Mti50Q20nqHVpyfHZ10:-Mtiek7d94poFgCtovCV:b-akar9w) (no related file):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

This network config caching system feels like something which should have both more generalisation and more conformance.  It doesn't feel correct to tie it to the platform operators, and it could conceptually apply to other configuration aspects.  It's also making the platform operator code about three times the complexity it would otherwise seem to need.

Maybe it's out of scope for this PR
</blockquote></details>

I don't think caching makes it any way bigger, most of the code is there to handle multiple resource types which is quite verbose without generics. 

Caching is a small piece of that, and yes, we can definitely extract it as something common as we see the next usecase for it.

---
___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 82 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthbwoP2JXSP9U4vpIX:-MtifMGE2Dxm9-RX6as1:b-896fix) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L82)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

s/address/operator/ ?
</blockquote></details>

Done.
___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 103 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthcGhc9vnQuPNTzCQA:-MtifMza3GqjrhPJYCVV:b-896fix) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L103)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

by failing the ... ?
</blockquote></details>

Done.
___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 113 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthcSS-1nLNaZ5GO61R:-MtifWl-COySyf8IwKms:b-896fix) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L113)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

s/addresses/operators/
</blockquote></details>

Done.
___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 125 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthcWQp5dOjvcfUC0Zj:-MtifXAA5YJKVIfzRibD:b-896fix) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L125)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

operators
</blockquote></details>

Done.
___
*[internal/app/machined/pkg/controllers/network/operator_merge.go, line 130 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthcYVI3eAOIBWfJ1LK:-MtifXdR2ACADyEf0W8m:b-896fix) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/operator_merge.go#L130)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

operators
</blockquote></details>

Done.
___
*[internal/app/machined/pkg/controllers/network/platform_config.go, line 102 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthdJVj8V9q8VNkqMAe:-MtifaTa4AX6PvKCLCq7:b-57ulam) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/platform_config.go#L102)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

This seems like a weird place for asserting an unrelated constant.  Is the controller not fully instantiated here?  If this is truly a constant which is not affected by anything else, should this go in the controller instantiation instead?
</blockquote></details>

There is no explicit controller instantiation  (zero value is enough). `StatePath` is used in unit-tests to override state path. Under "normal" instantiation this code just sets up proper default.
___
*[internal/app/machined/pkg/controllers/network/platform_config.go, line 184 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthqCcJEmdbNqmRznD7:-Mtig03zCcO8fQ-bKYZ_:bk8g7u7) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/platform_config.go#L184)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

Could this prioritisation just be handled by a config layer for caching... with a sufficiently broad resource type to force conflict?
</blockquote></details>

I don't think layers are a proper way to handle that. Layers are merged together, and we don't want to merge cached and live config; live config should replace cached version

E.g. cached might say "do DHCP on eth0", while live says "assign IP X to eth0", and we don't want them to be merged, we want one to replace another
___
*[internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go, line 180 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-Mti-TxfEfo7FwWhkR4w:-MtigKI32ZOk46N8SuF5:b-xm3mwb) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go#L180)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

AFAIK, IPv6 default routes' default metric is 1024.  I don't know what we're using elsewhere, but a route metric of 2048 is likely to be clobbered, if defaults are otherwise similar.
</blockquote></details>

I'm not sure why priority was set to 2048. But I kept the way it was, we can update it in the next PR.
___
*[internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go, line 247 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-Mti45AB6N_BIJOkBUvX:-MtigRck521n6hZ6UawI:bp5g2rp) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go#L247)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

I see that this is just copied from the previous implementation, but I don't understand the purpose.  Route metrics between IPv4 and IPv6 are meaningless; they will never be compared.  So why is this doubling the default route metric here?
</blockquote></details>

I agree with you, but I tried to avoid making changes.

**Review by Ulexus — APPROVED** [review]
> Reviewed 17 of 67 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4755)* status: all files reviewed, 1 unresolved discussion (waiting on @smira)

___
*[internal/app/machined/pkg/controllers/network/platform_config.go, line 184 at r1](https://reviewable.io/reviews/talos-systems/talos/4755#-MthqCcJEmdbNqmRznD7:-Mto6qKo3g6s61v6sEa_:bxy9b4l) ([raw file](https://github.com/talos-systems/talos/blob/31a23fc9696f0da330b6e02f1b547d6adca5cd6d/internal/app/machined/pkg/controllers/network/platform_config.go#L184)):*
<details><summary><i>Previously, smira (Andrey Smirnov) wrote…</i></summary><blockquote>

I don't think layers are a proper way to handle that. Layers are merged together, and we don't want to merge cached and live config; live config should replace cached version

E.g. cached might say "do DHCP on eth0", while live says "assign IP X to eth0", and we don't want them to be merged, we want one to replace another
</blockquote></details>

This does seem like something which could be generalised, though.  For instance, bootstrap networking  (just enough to get machineconfig, then go away entirely) including such things as kernel cmdline config.

That's all very much out of scope here, though.
___
*[internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go, line 131 at r2](https://reviewable.io/reviews/talos-systems/talos/4755#-Mto5tLt82wjLvUyaqXc:-Mto5tLuC4pZArQ1TwU7:b-y5pe1t) ([raw file](https://github.com/talos-systems/talos/blob/a64eddc7ee8f5af0cf77f9494600b8a629e924d4/internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go#L131)):*
> ```Go
> 			}
> 
> 			if !ip.DHCP {
> ```

nit:  implicit non-covered case:  `ip.DHCP && ip.Family == "IPv6"`

**Review by smira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4755)* status: all files reviewed, 1 unresolved discussion (waiting on @Ulexus)

___
*[internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go, line 131 at r2](https://reviewable.io/reviews/talos-systems/talos/4755#-Mto5tLt82wjLvUyaqXc:-MtrZuAdCNHIVYB7pOi6:b-up6y62) ([raw file](https://github.com/talos-systems/talos/blob/a64eddc7ee8f5af0cf77f9494600b8a629e924d4/internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go#L131)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

nit:  implicit non-covered case:  `ip.DHCP && ip.Family == "IPv6"`
</blockquote></details>

yep, it wasn't handled before my changes, not clear if it doesn't support DHCP6 or IPv6 is always static :shrug:

**Review by Ulexus — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4755)* status: all files reviewed, 1 unresolved discussion (waiting on @smira)

___
*[internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go, line 131 at r2](https://reviewable.io/reviews/talos-systems/talos/4755#-Mto5tLt82wjLvUyaqXc:-MtrguV37OhjjUj2P33c:bb5a1di) ([raw file](https://github.com/talos-systems/talos/blob/9ad5a67d21b0788d1b43f1bea8e39c003a4a8ecc/internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go#L131)):*
<details><summary><i>Previously, smira (Andrey Smirnov) wrote…</i></summary><blockquote>

yep, it wasn't handled before my changes, not clear if it doesn't support DHCP6 or IPv6 is always static :shrug: 
</blockquote></details>

Just add a comment to note?

**Review by Ulexus — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4755)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @smira)

**Pull request merged**
