### PR TITLE
feat: add routes, routing rules and nftables rules for KubeSpan

### PR DESCRIPTION
**Pull request by smira**
This concludes basic KubeSpan implementation.

Most of the code is from #3577 with some fixes and refactoring.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>
Signed-off-by: Seán C McCord <ulexus@gmail.com>
Co-authored-by: Seán C McCord <ulexus@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4241)

### CODE REVIEW

**Review by Ulexus — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4241)* status: all files reviewed, 3 unresolved discussions (waiting on @smira)

___
*[internal/app/machined/pkg/controllers/kubespan/nftables.go, line 28 at r1](https://reviewable.io/reviews/talos-systems/talos/4241#-MjfPof-9mKVDjah86iJ:-MjfPof06Lt7PG6sK5Ts:b-x5c3m2) ([raw file](https://github.com/talos-systems/talos/blob/a4452a1c4702ba23506d28b1a27cce3bd4546891/internal/app/machined/pkg/controllers/kubespan/nftables.go#L28)):*
> ```Go
> 	currentSet *netaddr.IPSet
> 
> 	// nfTable is a handle for the WgLAN root table
> ```

s/WgLan/KubeSpan/g
___
*[internal/app/machined/pkg/controllers/kubespan/nftables.go, line 57 at r1](https://reviewable.io/reviews/talos-systems/talos/4241#-MjfQ9Zh0lRtX8w0HRDU:-MjfQ9Zh0lRtX8w0HRDV:bcewm4l) ([raw file](https://github.com/talos-systems/talos/blob/a4452a1c4702ba23506d28b1a27cce3bd4546891/internal/app/machined/pkg/controllers/kubespan/nftables.go#L57)):*
> ```Go
> 	c := &nftables.Conn{}
> 
> 	// NB: sets should be flushed before new members because nftables will fail
> ```

Copy-paste:  this is not really relevant in this instance
___
*[internal/app/machined/pkg/controllers/kubespan/nftables.go, line 79 at r1](https://reviewable.io/reviews/talos-systems/talos/4241#-MjfQWa65utrXO-K6SLc:-MjfQWa65utrXO-K6SLd:bf4awor) ([raw file](https://github.com/talos-systems/talos/blob/a4452a1c4702ba23506d28b1a27cce3bd4546891/internal/app/machined/pkg/controllers/kubespan/nftables.go#L79)):*
> ```Go
> 	// if there are any conflicts between existing ranges and new ranges.
> 
> 	if m.targetSet4 != nil {
> ```

If the kernel already has the KubeSpan NFTables table but our nfTablesManager doesn't know it (for instance, it died and was restarted without cleanup), it seems we would be in a stuck state:  we wouldn't flush the sets/tables, but writing out the table may die due to the aforementioned conflicts.

Am I missing where the table is initiatlised / wiped before we get here, perhaps?  Or are these targetSet and nfTable values loaded at start somewhere (from the kernel, I mean)?

**Review by smira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4241)* status: all files reviewed, 3 unresolved discussions (waiting on @smira and @Ulexus)

___
*[internal/app/machined/pkg/controllers/kubespan/nftables.go, line 57 at r1](https://reviewable.io/reviews/talos-systems/talos/4241#-MjfQ9Zh0lRtX8w0HRDU:-Mjiup7J-6j6usBmRtzi:bkiterg) ([raw file](https://github.com/talos-systems/talos/blob/a4452a1c4702ba23506d28b1a27cce3bd4546891/internal/app/machined/pkg/controllers/kubespan/nftables.go#L57)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

Copy-paste:  this is not really relevant in this instance
</blockquote></details>

heh, I saw that, but forgot to remove
___
*[internal/app/machined/pkg/controllers/kubespan/nftables.go, line 79 at r1](https://reviewable.io/reviews/talos-systems/talos/4241#-MjfQWa65utrXO-K6SLc:-MjiuvFh6z37c4op_p10:b3oz53j) ([raw file](https://github.com/talos-systems/talos/blob/a4452a1c4702ba23506d28b1a27cce3bd4546891/internal/app/machined/pkg/controllers/kubespan/nftables.go#L79)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

If the kernel already has the KubeSpan NFTables table but our nfTablesManager doesn't know it (for instance, it died and was restarted without cleanup), it seems we would be in a stuck state:  we wouldn't flush the sets/tables, but writing out the table may die due to the aforementioned conflicts.

Am I missing where the table is initiatlised / wiped before we get here, perhaps?  Or are these targetSet and nfTable values loaded at start somewhere (from the kernel, I mean)?
</blockquote></details>

there's a `defer` block in the controller which calls `Cleanup` on any exit, and it should flush the state. but certainly there might be some room for improvement here? I guess we don't need the tables themselves, or in fact we can pre-create them? I might need to look into the code here

**Review by Ulexus — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @smira)

**Pull request merged**
