### PR TITLE
release(v0.8.2): prepare release

### PR DESCRIPTION
**Pull request by smira**
This is the official v0.8.2 release.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]

**Comment by smira** [comment]
upgrade tests passed in https://ci.dev.talos-systems.io/talos-systems/talos/14766

**Comment by smira** [comment]
successful full build: https://ci.dev.talos-systems.io/talos-systems/talos/14772

**Pull request merged**
