### PR TITLE
chore: add cloud image uploader (AWS AMIs for now)

### PR DESCRIPTION
**Pull request by smira**
It generates JSON file in the end with the upload results:

```
{"aws":{"regions":{"eu-central-1":{"arch":{"amd64":{"ami_id":"ami-0f559e06baf488ee1"},"arm64":{"ami_id":"ami-01edd1830a3c5d95c"}}},"eu-west-3":{"arch":{"amd64":{"ami_id":"ami-020f95a280c4c1c55"},"arm64":{"ami_id":"ami-0edcc7d694931a52c"}}}}}}
```

Regions, architectures can be modified as well.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
Full output:

```
go run . --artifacts-path=../../_out --tag v0.7.0 --aws-regions eu-central-1,eu-west-3
2020/11/19 00:43:58 aws: created bucket "talos-image-upload-56f9b91d-3190-4b6b-9ba7-b8b7b9d5a367" for eu-central-1
2020/11/19 00:43:58 aws: created bucket "talos-image-upload-f9bb3803-7b99-4a37-a9bc-b0574f5fe781" for eu-west-3
2020/11/19 00:47:22 aws: import into eu-central-1/amd64, image uploaded to S3
2020/11/19 00:47:23 aws: import into eu-central-1/amd64, task ID "import-snap-05db03a3d3de6f038"
2020/11/19 00:47:24 aws: import into eu-central-1/amd64, import snapshot 2%
2020/11/19 00:47:28 aws: import into eu-central-1/arm64, image uploaded to S3
2020/11/19 00:47:29 aws: import into eu-central-1/arm64, task ID "import-snap-05902c04a7ef4f1fa"
2020/11/19 00:47:29 aws: import into eu-central-1/arm64, import snapshot 2%
2020/11/19 00:47:39 aws: import into eu-west-3/amd64, image uploaded to S3
2020/11/19 00:47:40 aws: import into eu-west-3/amd64, task ID "import-snap-04bdbc2db68d7949c"
2020/11/19 00:47:40 aws: import into eu-west-3/amd64, import snapshot 2%
2020/11/19 00:47:41 aws: import into eu-west-3/arm64, image uploaded to S3
2020/11/19 00:47:41 aws: import into eu-west-3/arm64, task ID "import-snap-0e492dbdfee506148"
2020/11/19 00:47:41 aws: import into eu-west-3/arm64, import snapshot 2%
2020/11/19 00:48:10 aws: import into eu-west-3/amd64, import snapshot 5%
2020/11/19 00:48:24 aws: import into eu-central-1/amd64, import snapshot 18%
2020/11/19 00:48:29 aws: import into eu-central-1/arm64, import snapshot 5%
2020/11/19 00:48:40 aws: import into eu-west-3/amd64, import snapshot 35%
2020/11/19 00:48:41 aws: import into eu-west-3/arm64, import snapshot 35%
2020/11/19 00:48:54 aws: import into eu-central-1/amd64, import snapshot 32%
2020/11/19 00:48:59 aws: import into eu-central-1/arm64, import snapshot 32%
2020/11/19 00:49:10 aws: import into eu-west-3/amd64, import snapshot 72%
2020/11/19 00:49:11 aws: import into eu-west-3/arm64, import snapshot 43%
2020/11/19 00:49:24 aws: import into eu-central-1/amd64, import snapshot 35%
2020/11/19 00:49:29 aws: import into eu-central-1/arm64, import snapshot 35%
2020/11/19 00:49:40 aws: import into eu-west-3/amd64, import snapshot 94%
2020/11/19 00:49:41 aws: import into eu-west-3/arm64, import snapshot 94%
2020/11/19 00:50:10 aws: import into eu-west-3/amd64, snapshot ID "snap-0a0ee2666fbee00c5"
2020/11/19 00:50:11 aws: import into eu-west-3/amd64, deregistered image ID "ami-0586630c8617b4888"
2020/11/19 00:50:11 aws: import into eu-west-3/amd64, registered image ID "ami-020f95a280c4c1c55"
2020/11/19 00:50:24 aws: import into eu-central-1/amd64, import snapshot 40%
2020/11/19 00:50:29 aws: import into eu-central-1/arm64, import snapshot 37%
2020/11/19 00:50:42 aws: import into eu-west-3/arm64, snapshot ID "snap-0f6f1b057ead47bf3"
2020/11/19 00:50:42 aws: import into eu-west-3/arm64, registered image ID "ami-0edcc7d694931a52c"
2020/11/19 00:50:54 aws: import into eu-central-1/amd64, import snapshot 70%
2020/11/19 00:50:59 aws: import into eu-central-1/arm64, import snapshot 43%
2020/11/19 00:51:24 aws: import into eu-central-1/amd64, import snapshot 75%
2020/11/19 00:51:30 aws: import into eu-central-1/arm64, import snapshot 72%
2020/11/19 00:51:54 aws: import into eu-central-1/amd64, import snapshot 89%
2020/11/19 00:52:00 aws: import into eu-central-1/arm64, import snapshot 89%
2020/11/19 00:52:25 aws: import into eu-central-1/amd64, import snapshot 94%
2020/11/19 00:52:30 aws: import into eu-central-1/arm64, import snapshot 91%
2020/11/19 00:53:00 aws: import into eu-central-1/arm64, import snapshot 94%
2020/11/19 00:53:25 aws: import into eu-central-1/amd64, import snapshot 97%
2020/11/19 00:53:55 aws: import into eu-central-1/amd64, snapshot ID "snap-0d2c2a7ca6ba47607"
2020/11/19 00:53:56 aws: import into eu-central-1/amd64, deregistered image ID "ami-0e3a2ac7b871715fe"
2020/11/19 00:53:56 aws: import into eu-central-1/amd64, registered image ID "ami-0f559e06baf488ee1"
2020/11/19 00:54:00 aws: import into eu-central-1/arm64, import snapshot 97%
2020/11/19 00:54:30 aws: import into eu-central-1/arm64, snapshot ID "snap-03d1d2c1bfcbf549d"
2020/11/19 00:54:31 aws: import into eu-central-1/arm64, registered image ID "ami-01edd1830a3c5d95c"
{"aws":{"regions":{"eu-central-1":{"arch":{"amd64":{"ami_id":"ami-0f559e06baf488ee1"}
```

**Review by andrewrynhard — DISMISSED** [review]

**Review by Unix4ever — DISMISSED** [review]
:cool:

**Comment by smira** [comment]
Add

```
err = svc.WaitUntilBucketExists(&s3.HeadBucketInput{
    Bucket: aws.String(bucket),
})
```

**Pull request merged**
