### PR TITLE
docs: update wirguard guide

### PR DESCRIPTION
**Pull request by OGKevin**
# Pull Request

## What? (description)
The wireguard guide has a small typo in the structure example of the config.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [x] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by AlekSi — COMMENTED** [review]
May you also update it in 0.11 guide please?

**Comment by Unix4ever** [comment]
And also in 0.9, thanks!

**Comment by AlekSi** [comment]
Uh, sorry, I missed 0.9 somehow 😞

**Comment by Unix4ever** [comment]
No worries :)

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
