### PR TITLE
chore: replace gitmeta with direct `git` commands

### PR DESCRIPTION
**Pull request by smira**
`gimeta` might provide more flexibility/metadata, but at the same time
it is very slow on the repo. The most annoying to me is the delay when
doing autocompletion `make te<TAB>`.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
(I might have missed why `gitmeta` is important, I tried to replicate what it returns for tagged commits, no tags, dirty tree)

**Comment by andrewrynhard** [comment]
The idea with gitmeta was that we could enforce versioning standards that we have, and that we would have to copy over a number of different git commands with conditionals across the various projects we use. I haven’t implemented it yet but the plan was to enforce things like semver on our tags. The code is there I just haven’t had the time. Another thing we don’t make use of is the ability to use gitmeta for determining if we should push an image. In the build refactor I have out there we make use of a new feature in docker that allows the remote buildkit instance to push the newly built image with having to copy it back over to the client. This could speed up a number of our builds and reduce the amount of east-west traffic we have. We haven’t quite used gitmeta to it's full potential yet. I understand that it’s slow, and unfortunately that is because it uses the pure Golang implementation of libgit, which has a few bugs. I can port it over to use the C bindings to libgit2. If we could contain our business logic and semver enforcement in a single binary that doesn’t require copying around a bunch of raw git commands, then I would prefer that. Let me see if I can get the performance issue worked out when I wake up for the day in a few hours here. I don’t want to slow us down and I understand the motivation behind this PR, but I think I have a fix to male everyone happy. If I can’t get it done in a reasonable amount of time, let’s merge this.

**Comment by smira** [comment]
Thanks, Andrew, for the explanation. Makes perfect sense to me. 

I wonder if we need pure Go `gitmeta` or we could replace it with some shell script calling out to `git`? (If the performance issue can't be resolved). It seems at least we could get from `git` what we need at least without much trouble, which might also be good in some ways.

But I agree `gitmeta` is a good way to enforce consistent versioning across projects. So we can close this PR if things can be improved either way.

**Comment by andrewrynhard** [comment]
@smira Let's keep it open. The only thing I'm hesitant about with a shell script is handling server parsing. I'm sure its doable, but probably ugly as all hell. Let me see what I can get done today.

**Comment by andrewrynhard** [comment]
https://github.com/talos-systems/gitmeta/pull/10

**Pull request closed without merging**
