### PR TITLE
fix: validate bond slaves addressing

### PR DESCRIPTION
**Pull request by smira**
This extends network device machine configuration validation to make
sure that bond slaves don't have any addressing methods set, as this
might run into a conflict with the bond setup.

Also makes sure no interface is part of two bonds.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — COMMENTED** [review]
What is "addressing methods" here? DHCP? VIP?

**Comment by smira** [comment]
> What is "addressing methods" here? DHCP? VIP?

all of them, they shouldn't be set on slave interfaces

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
