### PR TITLE
feat: set interface MTU in DHCP mode even if DHCP is not successful

### LINKED ISSUE #2789: mtu setting is not applied if an interface is dhcp:true but fails to get ip from dhcp
## Bug Report
talos config network part:
```
- interfaces:
  mtu: 9000
  dhcp: true
  dhcpOptions:
    routeMetric: 352321536
- interface: eth1
  mtu: 9000
  dhcp: true
  dhcpOptions:
    routeMetric: 352321536
```

only eth0 got IPv4 from dhcp, eth1 uses ipv6 link local address, end results were:

```
root@dev~/ #talosctl interfaces |grep eth
10.129.186.67   4       eth0              f0:92:1c:16:83:80   9000    10.129.185.189/31
10.129.186.67   4       eth0              f0:92:1c:16:83:80   9000    fe80::f292:1cff:fe16:8380/64
10.129.186.67   5       eth1              f0:92:1c:16:83:84   1500    fe80::f292:1cff:fe16:8384/64
```

eth1 expects to get mtu 9000, no matter dhcp works or not.

### Environment

talos version: v0.7.0-beta.1
k8s version: v1.19.3

### PR DESCRIPTION
**Pull request by smira**
Fixes #2789

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
re-pushed #2823 without changes

**Review by rsmitty — APPROVED** [review]

**Pull request merged**
