### PR TITLE
docs: custom kernel build steps update

### PR DESCRIPTION
**Pull request by sergelogvinov**
## What? (description)

customizing kernel documentation update

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)
- [x] you ran lint markdown (`make lint-markdown`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]
Thanks @sergelogvinov! I take it the customization process is working out well for you?

**Comment by sergelogvinov** [comment]
To be honest, I spent about 1 hour to understand how make my custom kernel. I am not sure, my version will be good for all people. But I hope it helps for someone _))

**Review by smira — APPROVED** [review]

**Pull request merged**
