### PR TITLE
chore: move gRPC API to public

### PR DESCRIPTION
**Pull request by andrewrynhard**
In order for other projects to make use of our APIs, they must not
reside underneath the internal directory. This moves the protobuf
definitions to a top-level "api" directory and scopes them according to
their domain. This change also removes generated code from the gitignore
file so that users don't have to generate the code themseleves.

### CODE REVIEW

**Comment by smira** [comment]
I wonder if we should also promote `client` package from `osctl` to be more of top-level thing, as it provides nice Go wrappers for the API.

**Comment by andrewrynhard** [comment]
> I wonder if we should also promote `client` package from `osctl` to be more of top-level thing, as it provides nice Go wrappers for the API.

I was thinking the same. It would be nice for when we build out the UI. For example, in the `osctl df` output we calculate a number of things client side. I'd like to be able to do that using a common code base.

**Comment by andrewrynhard** [comment]
@smira ok if we follow up with another PR to make the client outside of `osctl`?

**Comment by smira** [comment]
> @smira ok if we follow up with another PR to make the client outside of `osctl`?

sure thing!

**Pull request merged**
