### PR TITLE
docs: overhaul all the docs

### PR DESCRIPTION
**Pull request by rsmitty**
This moves our docs to a hugo-based doc setup with docsy theme.

Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/5143)

### CODE REVIEW

**Comment by rsmitty** [comment]
deploy preview is here: https://deploy-preview-5143--talos-dev.netlify.app/

**Review by smira — APPROVED** [review]

**Pull request merged**
