### PR TITLE
fix: extramount should have `yaml:",inline"` tag

### PR DESCRIPTION
**Pull request by Unix4ever**
Otherwise yaml `encode` produces during validation:

```yaml
extraMounts:
  - mounts:
      destination: /var/local
      ...
```

Instead of:

```yaml
extraMounts:
  - destination: /var/local
    ...
```

Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>

### CODE REVIEW

**Review by smira — APPROVED** [review]
How did it work before??? We were encoding configs always

**Comment by Unix4ever** [comment]
> How did it work before??? We were encoding configs always

I've tried to figure that out, but I'm still not sure why it worked before.

**Comment by smira** [comment]
> > How did it work before??? We were encoding configs always
> 
> I've tried to figure that out, but I'm still not sure why it worked before.

could it be that our encoder is buggy and ignores `inline` ? (or works as if `inline` was always given?

**Pull request merged**
