### PR TITLE
fix(osctl): Generate correct config with master IPs

### PR DESCRIPTION
**Pull request by bradbeam**
Signed-off-by: Brad Beam <brad.beam@talos-systems.com>

### CODE REVIEW

**Comment by smira** [comment]
should we have a regression test for it? (as it got broken, probably this would keep it from breaking?)

**Comment by bradbeam** [comment]
Looks like I've got some index wonkiness to work out.

**Comment by andrewrynhard** [comment]
@bradbeam This good now? I think we need this for the release tomorrow?

**Comment by bradbeam** [comment]
Should be g2g ( excluding the tests ).

**Pull request merged**
