### PR TITLE
fix(init): Dont log an error when context canceled

### LINKED ISSUE #723: Clean up output from trustd canceled context
```
[   92.689238] [talos] retrieving needed files via trustd
[   92.792639] [talos] failed to read file path:"/etc/kubernetes/pki/sa.key" : rpc error: code = Canceled desc = context canceled
[   92.804606] [talos] failed to read file path:"/etc/kubernetes/pki/etcd/ca.crt" : rpc error: code = Canceled desc = context canceled
[   92.817014] [talos] failed to read file path:"/etc/kubernetes/pki/etcd/ca.crt" : rpc error: code = Canceled desc = context canceled
[   92.829410] [talos] failed to read file path:"/etc/kubernetes/pki/sa.key" : rpc error: code = Canceled desc = context canceled
[   92.841366] [talos] failed to read file path:"/etc/kubernetes/pki/etcd/ca.key" : rpc error: code = Canceled desc = context canceled
[   92.853754] [talos] failed to read file path:"/etc/kubernetes/audit-policy.yaml" : rpc error: code = Canceled desc = context canceled
[   92.866312] [talos] failed to read file path:"/etc/kubernetes/pki/front-proxy-ca.key" : rpc error: code = Canceled desc = context canceled
[   92.879304] [talos] failed to read file path:"/etc/kubernetes/encryptionconfig.yaml" : rpc error: code = Canceled desc = context canceled
[   92.892227] [talos] failed to read file path:"/etc/kubernetes/pki/front-proxy-ca.crt" : rpc error: code = Canceled desc = context canceled
[   92.905227] [talos] failed to read file path:"/etc/kubernetes/pki/front-proxy-ca.key" : rpc error: code = Canceled desc = context canceled
[   92.918234] [talos] failed to read file path:"/etc/kubernetes/audit-policy.yaml" : rpc error: code = Canceled desc = context canceled
[   92.930791] [talos] failed to read file path:"/etc/kubernetes/pki/front-proxy-ca.crt" : rpc error: code = Canceled desc = context canceled
[   92.943787] [talos] failed to read file path:"/etc/kubernetes/encryptionconfig.yaml" : rpc error: code = Canceled desc = context canceled
[   92.956698] [talos] failed to read file path:"/etc/kubernetes/pki/etcd/ca.key" : rpc error: code = Canceled desc = context canceled
[   92.969085] [talos] service[kubeadm](Preparing): Creating service runner
[   92.976225] [talos] failed to read file path:"/etc/kubernetes/pki/sa.pub" : rpc error: code = Canceled desc = context canceled
[   92.988257] [talos] failed to read file path:"/etc/kubernetes/pki/sa.pub" : rpc error: code = Canceled desc = context canceled
```

this has the potential to confuse users that things didn't complete successfully. we should check to see if the error is context canceled and suppress it.

### PR DESCRIPTION
**Pull request by bradbeam**
When we receive all the necessary files from trustd, we cancel the context. This
was treated as an error case and a message was logged accordingly. However,
this case was not really an error versus a signal to stop trying to fetch a
given file.

Fixes #723

Signed-off-by: Brad Beam <brad.beam@talos-systems.com>

### CODE REVIEW

**Comment by andrewrynhard** [comment]
@bradbeam I'm thinking we should cherry-pick this into v0.1. Thoughts?

**Comment by bradbeam** [comment]
We can but not yet. Working on some tests locally and this doesn't work.

```
# err
2019/07/06 14:36:33 rpc error: code = Canceled desc = context canceled
# context.Canceled
2019/07/06 14:36:33 context canceled
```
So need to think a bit more on how to unwrap this error from grpc.

**Comment by bradbeam** [comment]
`status.Convert(err).Code() == codes.Canceled` should do it, just need to tinker a bit.

**Comment by bradbeam** [comment]
Should be good to go. Merged in my test changes.

**Pull request merged**
