### PR TITLE
feat: upgrade Kubernetes default version to 1.19.4

### PR DESCRIPTION
**Pull request by smira**
k8s.io modules don't have 1.19.4 tag yet :(

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
probably we should backport this to 0.7

**Review by Unix4ever — DISMISSED** [review]

**Review by andrewrynhard — DISMISSED** [review]

**Comment by smira** [comment]
full integration was 99% green https://ci.dev.talos-systems.io/talos-systems/talos/12766/1/23

all the test passed, but single node on Cilium choked on sonobuoy

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
