### PR TITLE
backports: for v1.0.0-beta.2

### PR DESCRIPTION
**Pull request by smira**
PRs backported:

- #5108 
- #5128
- #5135 
- #5136 
- #5139 
- #5141 
- #5142 
- #5144 
- #5162 
- #5145 
- #5146
- #5129 

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/5164)

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
there are some issues with etcd recovery tests, I will fix it in `master` and backport it to 1.0 before the release

**Pull request merged**
