### PR TITLE
feat: update Kubernetes to v1.20.0-beta.2

### LINKED ISSUE #2829: upgrade k8s to 1.20-beta.2

### PR DESCRIPTION
**Pull request by smira**
Talos 0.8 is going to ship with K8s 1.20.x.

Changes to support new `control-plane` label.

Fixes #2829

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
Should be ready in general, but I need to fix up the upgrade docs (waiting for 0.8 docs).

**Comment by smira** [comment]
Successful e2e: https://ci.dev.talos-systems.io/talos-systems/talos/13092

**Review by andrewrynhard — DISMISSED** [review]

**Pull request merged**
