### PR TITLE
Add arm64 option to talosctl download docs

### LINKED ISSUE #4704: Missing `arm64` architecture download option in docs for `talosctl`
## Feature Request
Add the `talosctl` download for `arm64` in `quickstart` and `getting-started` chapters in the documentation.

### Description
After trying out to install `talosctl` on my M1 MacBook I saw that the documentation lacks of the code to download the `arm64` variant of it. To support the native `arm64` builds of `talosctl` I would suggest to add this option to the documentation

### PR DESCRIPTION
**Pull request by niklasmtj**
# Pull Request

## What? (description)
Resolves #4704 
This PR updates the `quickstart` and `getting-started` pages for `v0.13` and `v0.14` to show download options for `arm64` 

## Why? (reasoning)
The `talosctl` is available as a `arm64` binary but this is not yet publicated in the `getting-started` or `quickstart` documentation pages. To use the native version this PR adds this option in the docs

## Acceptance

Please use the following checklist:

- [x] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4705)

### CODE REVIEW

**Comment by smira** [comment]
```
#17 1.182 website/content/docs/v0.13/Introduction/quickstart.md:30 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

**Comment by smira** [comment]
`conform` is unhappy, tl;dr is having a single commit with DCO, and header should follow conventional commit format.

Don't worry about GPG signature, we'll fix it up before merging.

**Comment by niklasmtj** [comment]
I hope this is okay now. I'm still wondering about the `conform/commit/commit-body`. Is there something I can do about it?

**Comment by smira** [comment]
> I hope this is okay now. I'm still wondering about the `conform/commit/commit-body`. Is there something I can do about it?

yep, commit body shouldn't be empty, but I can fix it up for you when re-signing

**Comment by niklasmtj** [comment]
That would be great. Tell me if I can do something about it.

**Comment by smira** [comment]
Note for myself: if #4716 goes first, also copy changes to 0.15 docs.

**Review by smira — APPROVED** [review]
thank you!

**Pull request merged**
