### PR TITLE
go.mod: bump github.com/mdlayher/arp@latest

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

# Pull Request

## What? (description)

Newest version of github.com/mdlayher/arp backed by the improved https://github.com/mdlayher/packet package. There's no stable release of arp yet but I'd like to get back around to that now that I'm stabilizing underlying pieces.

## Why? (reasoning)

I've deprecated mdlayher/raw and am trying to upgrade downstream folks who I've found using my work.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

Sorry, just a `go build ./...` here.

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/5036)

### CODE REVIEW

**Review by smira — APPROVED** [review]
thanks for updating!

**Comment by mdlayher** [comment]
No problem! Thanks for amending for the conformance check.

**Pull request merged**
