### PR TITLE
fix: move etcd PKI under /system/secrets

### LINKED ISSUE #3944: move etcd PKI under system/secrets
## Feature Request

Today we write down etcd PKI files under `/etc/kubernetes` for historical reasons.

It will be easier to protect those files if we move it to now standard `/system/secrets` location (since 0.9 all Kuberntes PKI goes there).

### Description

These files are written down by `services/etcd.go` each time etcd starts, so it's a matter of updating paths in etcd args and code that writes them down.

As Talos upgrade wipes the ephemeral partition, we don't have to remove `/etc/kubernetes` etcd PKI files, after an upgrade they will be gone. (What about upgrade with --preserve?)

As bonus point, review what's left in `/etc`.

### PR DESCRIPTION
**Pull request by smira**
Fixes #3944

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Comment by smira** [comment]
```
$ talosctl ls -lr -n 172.20.0.2 /etc/kubernetes
NODE         MODE         SIZE(B)   LASTMOD           NAME
172.20.0.2   d---------   108       Aug 10 23:50:04   .
172.20.0.2   -rw-------   1052      Aug 10 23:49:26   bootstrap-kubeconfig
172.20.0.2   -rw-------   1279      Aug 10 23:50:04   kubeconfig-kubelet
172.20.0.2   -rw-------   963       Aug 10 23:49:26   kubelet.yaml
172.20.0.2   drwxr-xr-x   114       Aug 10 23:50:08   manifests
172.20.0.2   -rw-------   3950      Aug 10 23:50:08   manifests/talos-kube-apiserver.yaml
172.20.0.2   -rw-------   2365      Aug 10 23:50:08   manifests/talos-kube-controller-manager.yaml
172.20.0.2   -rw-------   1655      Aug 10 23:50:08   manifests/talos-kube-scheduler.yaml
172.20.0.2   drwx------   20        Aug 10 23:49:26   pki
172.20.0.2   -r-x------   595       Aug 10 23:49:26   pki/ca.crt
```

**Review by andrewrynhard — APPROVED** [review]

**Comment by andrewrynhard** [comment]
Do we need to clean up any existing ones in the case of persistent upgrade?

**Comment by smira** [comment]
> Do we need to clean up any existing ones in the case of persistent upgrade?

Good question, let me add that, should be easy enough

**Comment by smira** [comment]
> Do we need to clean up any existing ones in the case of persistent upgrade?

now with cleanup added

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
