### PR TITLE
docs: add install and troubleshooting section in firecracker getting started

### PR DESCRIPTION
**Pull request by zerodayz**
# Pull Request

    docs: add installation chapter to firecracker getting started
    docs: add troubleshooting chapter to firecracker getting started

## What? (description)

Add installation/troubleshooting chapters to firecracker getting started guide.

## Why? (reasoning)

Missing steps in the getting started guide as discussed in https://github.com/talos-systems/talos/issues/2062

## Acceptance

Please use the following checklist:

- [X] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2064)

### CODE REVIEW

**Comment by andrewrynhard** [comment]
@zerodayz Thank you! This looks great 👍 . All we need to do now is get `make conformance` passing. I'm not sure why the Netlify build is failing, but I can look into it.

**Comment by andrewrynhard** [comment]
@zerodayz Also looks like `make lint-markdown` is failing.

**Comment by zerodayz** [comment]
@andrewrynhard Do you want me to squash those two into one? I wanted to make them distinguishable from each other, but I guess it's easier to manage as one commit?

**Comment by zerodayz** [comment]
Yes `make lint-markdown` is failing. I have run the command and can see there are some failed tests for example
```
$ sudo
```
I will remove the dollar sign, the idea of $ and # was to give information whether the command is run as root or as user.

**Comment by andrewrynhard** [comment]
> @andrewrynhard Do you want me to squash those two into one? I wanted to make them distinguishable from each other, but I guess it's easier to manage as one commit?

@zerodayz Yes please. We enforce this for all PRs. Helps us keep the commit history nice and clean.

**Comment by andrewrynhard** [comment]
@zerodayz Also, make sure to commit with the `-s` flags. It is the DCO agreement that we require for legal reasons. A simple body to the commit is also required, to give us more context as to why the changes were needed

**Comment by andrewrynhard** [comment]
Thanks @zerodayz . This is great 👍 .

**Pull request merged**
