### PR TITLE
fix: wrap etcd address URLs with formatting

### LINKED ISSUE #2120: Allow etcd to operate in an IPv6-only environment
## Feature Request

There are a number of places which still presume etcd will run in an environment which has IPv4 addresses, which is not always the case.  We need to remove these assumptions.

### PR DESCRIPTION
**Pull request by Ulexus**
Make certain that all etcd address URLs are properly wrapped to handle
IPv6 addresses.

Fixes #2120

Signed-off-by: Seán C McCord <ulexus@gmail.com>

# Pull Request

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2122)

### CODE REVIEW

**Comment by andrewrynhard** [comment]
@Ulexus Is this still a draft. I know we chatted yesterday about this, and that etcd was working with this change.

**Comment by Ulexus** [comment]
Thanks, yes.  This should be good, I just forgot to convert it.

**Pull request merged**
