### PR TITLE
feat: build talosctl for ARM64

### PR DESCRIPTION
**Pull request by andrewrynhard**
This adds an ARM64 build of `talosctl`.

### CODE REVIEW

**Comment by dave93cab** [comment]
Hi Andrew,

I managed to build from your repo. Turns out this box is ARMv7 but was trivial to get it to build for that too. Let me know if you still think this is reasonable for inclusion and if you need a PR. I'm not too hot on Dockerfile/Makefiles. Is there a way of looping over a dictionary of arches and GO parameters to remove the redundancy? I can see how you would do it inside the FROM base section but not sure how you would have something that works inside as well as outside that for the COPY part.

```
FROM base AS talosctl-linux-armv7-build
ARG SHA
ARG TAG
ARG ARTIFACTS
ARG VERSION_PKG="github.com/talos-systems/talos/pkg/version"
ARG MGMT_HELPERS_PKG="github.com/talos-systems/talos/cmd/talosctl/pkg/mgmt/helpers"
WORKDIR /src/cmd/talosctl
RUN --mount=type=cache,target=/.cache/go-build GOOS=linux GOARCH=arm GOARM=7 go build -ldflags "-s -w -X ${VERSION_PKG}.Name=Client -X ${VERSION_PKG}.SHA=${SHA} -X ${VERSION_PKG}.Tag=${TAG} -X ${MGMT_HELPERS_PKG}.ArtifactsPath=${ARTIFACTS}" -o /talosctl-linux-armv7
RUN chmod +x /talosctl-linux-armv7

FROM scratch AS talosctl-linux
COPY --from=talosctl-linux-amd64-build /talosctl-linux-amd64 /talosctl-linux-amd64
COPY --from=talosctl-linux-arm64-build /talosctl-linux-arm64 /talosctl-linux-arm64
COPY --from=talosctl-linux-armv7-build /talosctl-linux-armv7 /talosctl-linux-armv7
```

**Comment by andrewrynhard** [comment]
@dave93cab I'm not too concerned just yet about repeating docker statements for each arch. I can throw something up for v7. Will piing you in the PR.

**Pull request merged**
