### PR TITLE
feat: move to ECDSA keys for all Kubernetes/etcd certs and keys 

### PR DESCRIPTION
**Pull request by smira**
ECDSA keys are smaller which decreases Talos config size, they are more
efficient in terms of key generation, signing, etc., so it makes boot
performance better (and config generation as well).

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
need to preserve RSA generation for upgrade tests (at the very least)

**Review by rsmitty — APPROVED** [review]

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
