### PR TITLE
chore: don't run unit-tests and image build steps concurrently

### PR DESCRIPTION
**Pull request by smira**
The idea is that it should probably reduce number of CI failures on loop
device being busy.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/3803)

### CODE REVIEW

**Review by AlekSi — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]

**Comment by AlekSi** [comment]
```
#163 8.545 === RUN   TestManifestSuite
#163 8.545 === RUN   TestManifestSuite/TestExecuteManifestClean
#163 8.545     manifest_test.go:62: Using /dev/loop1
#163 8.545     manifest_test.go:84: test not supported under buildkit as partition devices are not propagated from /dev
#163 8.545 === RUN   TestManifestSuite/TestExecuteManifestForce
#163 8.545     manifest_test.go:62: Using /dev/loop2
#163 8.545     manifest_test.go:64: 
#163 8.545         	Error Trace:	manifest_test.go:64
#163 8.545         	            				suite.go:148
#163 8.545         	Error:      	Received unexpected error:
#163 8.545         	            	device or resource busy
#163 8.545         	Test:       	TestManifestSuite/TestExecuteManifestForce
#163 8.545     manifest_test.go:71: 
#163 8.545         	Error Trace:	manifest_test.go:71
#163 8.545         	            				suite.go:141
#163 8.545         	            				panic.go:613
#163 8.545         	            				testing.go:741
#163 8.545         	            				manifest_test.go:64
#163 8.545         	            				suite.go:148
#163 8.545         	Error:      	Received unexpected error:
#163 8.545         	            	no such device or address
#163 8.545         	Test:       	TestManifestSuite/TestExecuteManifestForce
#163 8.545 === RUN   TestManifestSuite/TestExecuteManifestPreserve
#163 8.545     manifest_test.go:62: Using /dev/loop2
#163 8.545     manifest_test.go:64: 
#163 8.545         	Error Trace:	manifest_test.go:64
#163 8.545         	            				suite.go:148
#163 8.545         	Error:      	Received unexpected error:
#163 8.545         	            	device or resource busy
#163 8.545         	Test:       	TestManifestSuite/TestExecuteManifestPreserve
#163 8.545     manifest_test.go:71: 
#163 8.545         	Error Trace:	manifest_test.go:71
#163 8.545         	            				suite.go:141
#163 8.545         	            				panic.go:613
#163 8.545         	            				testing.go:741
#163 8.545         	            				manifest_test.go:64
#163 8.545         	            				suite.go:148
#163 8.545         	Error:      	Received unexpected error:
#163 8.545         	            	no such device or address
#163 8.545         	Test:       	TestManifestSuite/TestExecuteManifestPreserve
#163 8.545 === RUN   TestManifestSuite/TestTargetInstall
#163 8.545     manifest_test.go:62: Using /dev/loop2
#163 8.545     manifest_test.go:64: 
#163 8.545         	Error Trace:	manifest_test.go:64
#163 8.545         	            				suite.go:148
#163 8.545         	Error:      	Received unexpected error:
#163 8.545         	            	device or resource busy
#163 8.545         	Test:       	TestManifestSuite/TestTargetInstall
#163 8.545     manifest_test.go:71: 
#163 8.545         	Error Trace:	manifest_test.go:71
#163 8.545         	            				suite.go:141
#163 8.545         	            				panic.go:613
#163 8.545         	            				testing.go:741
#163 8.545         	            				manifest_test.go:64
#163 8.545         	            				suite.go:148
#163 8.545         	Error:      	Received unexpected error:
#163 8.545         	            	no such device or address
#163 8.545         	Test:       	TestManifestSuite/TestTargetInstall
#163 8.545 --- FAIL: TestManifestSuite (0.03s)
#163 8.545     --- SKIP: TestManifestSuite/TestExecuteManifestClean (0.03s)
#163 8.545     --- FAIL: TestManifestSuite/TestExecuteManifestForce (0.00s)
#163 8.545     --- FAIL: TestManifestSuite/TestExecuteManifestPreserve (0.00s)
#163 8.545     --- FAIL: TestManifestSuite/TestTargetInstall (0.00s)
#163 8.545 FAIL
```

**Comment by smira** [comment]
It is unrelated to this PR failure which I described in details in the channel. I will close this PR, as I don't think it fixes anything

**Pull request closed without merging**
