### PR TITLE
feat: update Kubernetes to 1.21.1

### PR DESCRIPTION
**Pull request by smira**
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
k8s doesn't have Go modules tagged (once again), so not bumping these

**Review by rsmitty — APPROVED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
