### PR TITLE
feat: implement ephemeral partition encryption

### PR DESCRIPTION
**Pull request by Unix4ever**
This PR introduces the first part of disk encryption support.
New config section `systemDiskEncryption` was added into MachineConfig.
For now it contains only Ephemeral partition encryption.

Encryption itself supports two kinds of keys for now:
- node id deterministic key.
- static key which is hardcoded in the config and mainly used for test
purposes.

Talosctl cluster create can now be told to encrypt ephemeral partition
by using `--encrypt-ephemeral` flag.

Additionally:
- updated pkgs library version.
- changed Dockefile to copy cryptsetup deps from pkgs.

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Review by smira — COMMENTED** [review]
Forgot to finalize my review

**Pull request merged**
