### PR TITLE
feat: check downloaded config

### PR DESCRIPTION
**Pull request by sergelogvinov**
Check downloaded config if it has wrong format switch to maintenance mode

This is prevent infinity reboot instance if metadata has wrong format(data)

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by smira** [comment]
I'm not sure this is a good idea from security perspective: it effectively allows to drop into maintenance mode without auth and upload any new machine configuration. 

We tried to limit maintentance mode to _empty_ config scenario.

**Comment by andrewrynhard** [comment]
> I'm not sure this is a good idea from security perspective: it effectively allows to drop into maintenance mode without auth and upload any new machine configuration.
> 
> We tried to limit maintentance mode to _empty_ config scenario.

I had exactly this drafted. I agree 100%. If we can drop into maintenance mode with auth, that might work.

**Comment by smira** [comment]
So one of the potential problems might be updating Talos and new Talos version (due to some bug) considers machine config invalid and all of a sudden drops into maintenance mode.

Yes, we default to config being persisted, etc., but that doesn't mean it can't happen if we combine more things together.

**Comment by sergelogvinov** [comment]
Yep, I thought about this case...

If you clean the STATE partition (hack the container-pod), instance switch to maintenance mode too :(
It was my main point. 

this PR just add capabilities to recover the node or helps to deploy/debug new cluster.

Solutions:
* add certificate validation in maintenance mode (if we cat get machine.ca.crt) - case if new version update broken something
* use META partition to set flag (first install well done) witch disable maintenance mode at all.

**Comment by andrewrynhard** [comment]
> Yep, I thought about this case...
> 
> If you clean the STATE partition (hack the container-pod), instance switch to maintenance mode too :(
> It was my main point.
> 
> this PR just add capabilities to recover the node or helps to deploy/debug new cluster.
> 
> Solutions:
> 
> * add certificate validation in maintenance mode (if we cat get machine.ca.crt) - case if new version update broken something
> * use META partition to set flag (first install well done) witch disable maintenance mode at all.

What about a kernel arg that can force Talos into maintenance mode? So someone can edit boot args in the grub menu if they need to.

**Comment by smira** [comment]
we had an issue from @Ulexus about this #2980

also another idea was to add an API which will force to maintenance mode on reboot (e.g. to wipe the filesystem)

**Comment by sergelogvinov** [comment]
I am going to close this PR,

Continue discussion will here #4214

**Pull request closed without merging**
