### PR TITLE
feat: implement extension services

### LINKED ISSUE #4694: running arbitrary user containers
First iteration: support only containers with read-only root filesystem which already resides on the rootfs: `/usr/local/lib/containers/<name>/`. Container configuration should be in the `/usr/local/etc/containers/<name>.yaml`. 

Such service can be either injected by producing a custom build of Talos or by using system extensions.

Spec:

```yaml
name: foo
container:
  entrypoint: ./foo 
  # rootfs derived automatically from `name`: /lib/containers/foo
  args:
     - blah
     - blah
  mounts:
     - # embed here oci.Mount
depends:
   - service: cri
   - file: /run/machined/machined.sock
   - network:
       - address
       - connectivity
       - hostname
       - etcfiles
restart: never|always
```

As a demo system extension we can do a simple Go "Hello world" webserver.

We need also docs on how to use this feature.

Defaults which are not configurable:

* UID/GID: 0/0
* sharing only network namespace with the host
* OOM score - higher than Talos core services, but lower than CRI pods
* seccomp profile - enabled by default
* Linux capabilities - `*` (don't drop any)

### PR DESCRIPTION
**Pull request by smira**
Fixes #4694

User services run alongside with Talos system services.
Every user service container root filesystem should be already present
in the Talos root filesystem.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4998)

### CODE REVIEW

**Comment by JAORMX** [comment]
Do you mind adding a little more context in the PRs description? As someone interested in reviewing, it's a little hard to check this out without enough context.

**Comment by frezbo** [comment]
@JAORMX this PR would allow running additional services alongside talos augmented by use of system extensions, [example service](https://github.com/talos-systems/extensions/tree/main/examples/hello-world-service) or by building a custom version of talos

**Comment by smira** [comment]
> Do you mind adding a little more context in the PRs description? As someone interested in reviewing, it's a little hard to check this out without enough context.

PR references issue #4694 which describes the design. Documentation will be part of the PR as soon as it is finished.

**Review by frezbo — APPROVED** [review]
:heart:

**Review by andrewrynhard — APPROVED** [review]
IIUC we overlay extensions from / to /?

**Review by Ulexus — APPROVED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/talos-systems/talos/4998)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @smira)

**Comment by smira** [comment]
> IIUC we overlay extensions from / to /?

yeah, we do

**Pull request merged**
