### PR TITLE
feat: make kubelet service apply changes immediately

### LINKED ISSUE #3690: COSI controller to run kubelet
## Feature Request

High-level plan is to take the `Pre` step out of the `system/services/kubelet.go` and rewrite it as a controller.

Controller will restart `kubelet` service when kubelet configuration changes.

### Description

`KubeletConfigController` listens for machine configuration changes and generates kubelet configuration which should include extra args, nodename, node IPs, kubelet image, extra mounts, etc. The configuration is generated as a resource.

`KubeletServiceController` listens for kubelet configuration changes (as a resource), renders config as files and restarts `kubelet` services as needed.

We should allow `--immediate` changes to the machine configuration.

(Note for later: we should handle the case when the node hostname / IP address changes and look into removing the kubelet cert to get it reissued)

### PR DESCRIPTION
**Pull request by smira**
Fixes #3690

The gist is that `kubelet` service code only manages the container
lifecycle, while `kubelet` configuration is managed now in the
controllers and resources.

New resources:

* `secrets.Kubelet` contains Kubelet PKI derived directly from the
machine configuration
* `k8s.KubeletConfig` contains Kubelet non-secret config derived
directly from the machine configuration
* `k8s.NodeIPConfig` contains configuration on picking up Node IP for
the kubelet (from machine configuration)
* `k8s.NodeIP` contains actual Node IPs picked from the node addresses
based on `NodeIPConfig`
* `k8s.KubeletSpec` contains final `kubelet` container configuration,
including merged arguments, KubeletConfig, etc. It is derived from
`KubeletConfig`, `Nodename` and `NodeIP`.

Final controller `KubeletServiceController` writes down configuration
and PKI to disk, and manages restart/start of the `kubelet` service
which is a pure wrapper around container lifecycle.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4638)

### CODE REVIEW

**Comment by smira** [comment]
I want to enable kubelet upgrade in `upgrade-k8s` as a follow-up PR

**Comment by smira** [comment]
Sample resources:

```sh
$ talosctl -n 172.20.0.2 get kubeletsecret -o yaml
node: 172.20.0.2
metadata:
    namespace: secrets
    type: KubeletSecrets.secrets.talos.dev
    id: kubelet
    version: 1
    owner: secrets.KubeletController
    phase: running
    created: 2021-12-02T21:00:05Z
    updated: 2021-12-02T21:00:05Z
spec:
    endpoint:
        scheme: https
        opaque: ""
        user: null
        host: 172.20.0.1:6443
        path: ""
        rawpath: ""
        forcequery: false
        rawquery: ""
        fragment: ""
        rawfragment: ""
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRDZ0F3SUJBZ0lSQUl3K2x2UlIzMjZvMi9GQ1lIc3VKclF3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlNVEV5TURJeU1EVTVNelJhRncwek1URXhNekF5TURVNQpNelJhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRBY1I0USsyZGpadVF4YWRmaFMwZ1c4QllLQjREQ2lIdVdwNGVCSk1kRkptNnBrM2pQQ01HbklpNEYKVW1GY1VkSDBXZC8zSkpVbStBOThRSU5lR2pwMm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGSGV5QlZ2aEtSK29tMGtTRjVMMHZBNmo5OWJiTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFER1lQK0oKaFR6dVpTM0M2UnRnVUlZSG9DVi9tQkcrUWEzMTJITUduU0ptOXdJaEFONjdQaVZNeit6c2xLOE81VFgxUzRrQwo5RkhjM2VueXM0Nlh5NThreURaWAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVByYngzMmZ0dEZvQzc3SzN1Rmp1RTRnQzBYUzNHTUhvM3l5YUh3QVIxcGRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFd0hFZUVQdG5ZMmJrTVduWDRVdElGdkFXQ2dlQXdvaDdscWVIZ1NUSFJTWnVxWk40endqQgpweUl1QlZKaFhGSFI5Rm5mOXlTVkp2Z1BmRUNEWGhvNmRnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    bootstrapTokenID: 0z481n
    bootstrapTokenSecret: zmwptl93bpzerwqm
```

```sh
$ talosctl -n 172.20.0.2 get kubeletconfig -o yaml
node: 172.20.0.2
metadata:
    namespace: k8s
    type: KubeletConfigs.kubernetes.talos.dev
    id: kubelet
    version: 1
    owner: k8s.KubeletConfigController
    phase: running
    created: 2021-12-02T21:00:05Z
    updated: 2021-12-02T21:00:05Z
spec:
    image: ghcr.io/talos-systems/kubelet:v1.23.0-rc.0
    clusterDNS:
        - 10.96.0.10
    clusterDomain: cluster.local
    cloudProviderExternal: false
```

```sh
$ talosctl -n 172.20.0.2 get nodeipconfig -o yaml
node: 172.20.0.2
metadata:
    namespace: k8s
    type: NodeIPConfigs.kubernetes.talos.dev
    id: kubelet
    version: 1
    owner: k8s.NodeIPConfigController
    phase: running
    created: 2021-12-02T21:00:05Z
    updated: 2021-12-02T21:00:05Z
spec:
    validSubnets:
        - 0.0.0.0/0
    excludeSubnets: []
```

```sh
$ talosctl -n 172.20.0.2 get nodeip -o yaml
node: 172.20.0.2
metadata:
    namespace: k8s
    type: NodeIPs.kubernetes.talos.dev
    id: kubelet
    version: 1
    owner: k8s.NodeIPController
    phase: running
    created: 2021-12-02T21:00:05Z
    updated: 2021-12-02T21:00:05Z
spec:
    addresses:
        - 172.20.0.2
```

```sh
$ talosctl -n 172.20.0.2 get kubeletspec -o yaml
node: 172.20.0.2
metadata:
    namespace: k8s
    type: KubeletSpecs.kubernetes.talos.dev
    id: kubelet
    version: 1
    owner: k8s.KubeletSpecController
    phase: running
    created: 2021-12-02T21:00:05Z
    updated: 2021-12-02T21:00:05Z
spec:
    image: ghcr.io/talos-systems/kubelet:v1.23.0-rc.0
    args:
        - --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubeconfig
        - --cert-dir=/var/lib/kubelet/pki
        - --config=/etc/kubernetes/kubelet.yaml
        - --container-runtime=remote
        - --container-runtime-endpoint=unix:///run/containerd/containerd.sock
        - --hostname-override=talos-default-master-1
        - --kubeconfig=/etc/kubernetes/kubeconfig-kubelet
        - --node-ip=172.20.0.2
    config:
        address: 0.0.0.0
        apiVersion: kubelet.config.k8s.io/v1beta1
        authentication:
            anonymous:
                enabled: false
            webhook:
                cacheTTL: 0s
                enabled: true
            x509:
                clientCAFile: /etc/kubernetes/pki/ca.crt
        authorization:
            mode: Webhook
            webhook:
                cacheAuthorizedTTL: 0s
                cacheUnauthorizedTTL: 0s
        cgroupRoot: /
        clusterDNS:
            - 10.96.0.10
        clusterDomain: cluster.local
        cpuManagerReconcilePeriod: 0s
        evictionPressureTransitionPeriod: 0s
        failSwapOn: false
        fileCheckFrequency: 0s
        httpCheckFrequency: 0s
        imageMinimumGCAge: 0s
        kind: KubeletConfiguration
        kubeletCgroups: /podruntime/kubelet
        logging:
            format: json
            options:
                json:
                    infoBufferSize: "0"
        memorySwap: {}
        nodeStatusReportFrequency: 0s
        nodeStatusUpdateFrequency: 0s
        oomScoreAdj: -450
        port: 10250
        rotateCertificates: true
        runtimeRequestTimeout: 0s
        serializeImagePulls: false
        shutdownGracePeriod: 0s
        shutdownGracePeriodCriticalPods: 0s
        staticPodPath: /etc/kubernetes/manifests
        streamingConnectionIdleTimeout: 0s
        syncFrequency: 0s
        systemCgroups: /system
        systemReserved:
            cpu: 50m
            ephemeral-storage: 256Mi
            memory: 128Mi
            pid: "100"
        volumeStatsAggPeriod: 0s
```

**Comment by smira** [comment]
And yes, we can reconfigure, upgrade, downgrade, etc. kubelet without node reboot :magic_wand:

**Review by rsmitty — APPROVED** [review]

**Review by frezbo — APPROVED** [review]

**Pull request merged**
