### PR TITLE
chore: bump dependencies via dependabot

### PR DESCRIPTION
**Pull request by smira**
PRs #3336 #3337 #3338 #3339

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by AlekSi** [comment]
https://github.com/golang/protobuf/releases/tag/v1.5.0
https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.25.0
https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.26.0

I think we should also update tools repo

**Comment by smira** [comment]
> I think we should also update tools repo

done

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
