### PR TITLE
chore: bump Go module dependencies

### PR DESCRIPTION
**Pull request by smira**
This bumps all the dependencies that can be bumped with minor fixups in
the code.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Comment by smira** [comment]
integration passed except for the known issue with renamed resources https://ci.dev.talos-systems.io/talos-systems/talos/15549/5/1

**Pull request merged**
