### PR TITLE
docs: update components.md

### PR DESCRIPTION
**Pull request by vladdoster**
# Pull Request

- fix spelling
- increase readability
- fix grammar
- reduce verbiage

## What? (description)

Reduce friction in knowledge transfer.

## Why? (reasoning)

The document was hard to understand while reading.

## Acceptance

Please use the following checklist:

- [x] you linked an issue (if applicable)
- [x] you included tests (if applicable)
- [x] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [x] you generated documentation (`make docs`)
- [x] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]
LGTM 👍

**Review by smira — DISMISSED** [review]

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
