### PR TITLE
fix: fail on muliple nodes for commands which don't support it

### LINKED ISSUE #1663: [osctl] fail fast on multiple nodes if command is not ready
All the `apid` requests can successfully be passed to multiple nodes, but not all the command implementations are ready to handle the response properly.

Until we get a proper fix, makes sense to do quick check/fail mode in the following commands:

* `copy`
* `list`
* `read`
* `kubeconfig`

### PR DESCRIPTION
**Pull request by smira**
Fixes #1663

(I believe it's 0.3 backport strong candidate).

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by andrewrynhard** [comment]
> (I believe it's 0.3 backport strong candidate).

**Comment by andrewrynhard** [comment]
I agree with all of these except `list`. FWIW, it works fine today, with the exception that the node name is missing.

**Comment by smira** [comment]
> I agree with all of these except `list`. FWIW, it works fine today, with the exception that the node name is missing.

up to you, I agree it doesn't break badly, but I thought adding new column (I was mostly worried about mode without `-l` which just prints the names) might be breaking change for 0.3? 

so I think there are three options:

1. keep list failing on multi-node
2. keep it as it is today (no failures, but no node)
3. fix list to print node names

**Comment by smira** [comment]
> I agree with all of these except `list`. FWIW, it works fine today, with the exception that the node name is missing.

removed `list` from this PR, will fix `list` on multi-nodes in the follow-up PR

**Pull request merged**
