### PR TITLE
feat: talosctl fish completion support

### PR DESCRIPTION
**Pull request by nberlee**
Generate talosctl completion for Fish

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/4580)

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
@nberlee I already fixed it, but just to make things easier next time: `talosctl` docs are auto-generated, so you can do simply `make docs` to get them updated

**Comment by nberlee** [comment]
Ah, thx! I will remember that for next time. Thats way easier

**Comment by smira** [comment]
thank you!

**Pull request merged**
