### PR TITLE
Containerd config refactoring

### PR DESCRIPTION
**Pull request by sergelogvinov**
# Pull Request

#3836

[Containerd registry-host documentation](https://github.com/containerd/containerd/blob/main/docs/hosts.md) 

* resolve startup containerd warnings messages
* folder based TLS auth/mirror endpoints
* can use insecure registry

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/3975)

### CODE REVIEW

**Comment by AlekSi** [comment]
Please make `make conformance` happy: it should be a single commit with a non-empty message body, etc.

**Comment by sergelogvinov** [comment]
Thank you for your notice, i am not ready yet )

**Comment by smira** [comment]
I don't quite like new containerd CRI plugin config format for registries, as it's multiple files now. I wonder if we should at least try to put config files to `/system/secrets` to make it ephemeral, so that we can clear extra files on reboot (at least).

Plus my concern is that if we put hostname into file paths, it might contian entries like `foo/../bar` which allows some random files overwrites (there are other ways to do that, but still). I don't have a good answer for that right now.

**Comment by sergelogvinov** [comment]
Yep, store configs to /system/secrets got idea, I've got this limitation https://github.com/talos-systems/talos/blob/master/internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go#L959 (create operation not allowed outside of /var)

foo/../bar - yes, we can prevent it

**Comment by sergelogvinov** [comment]
> 
> Plus my concern is that if we put hostname into file paths, it might contian entries like `foo/../bar` which allows some random files overwrites (there are other ways to do that, but still). I don't have a good answer for that right now.

I am using this method to get folder name.
```go
u, err := url.Parse(registryHostURL)

...

filepath.Join(constants.CRIContainerdConfigDir, u.Host, "hosts.toml"),
```

So it resolves **/../..** hacks

**Comment by smira** [comment]
Should be replaced by #4825

**Pull request closed without merging**
