### PR TITLE
release(v0.7.0-alpha.2): prepare release

### PR DESCRIPTION
**Pull request by smira**
This is the official v0.7.0-alpha.2 release.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2539)

### CODE REVIEW

**Review by rsmitty — DISMISSED** [review]

**Comment by smira** [comment]
rebased against latest master

**Review by Ulexus — APPROVED** [review]

**Pull request merged**
