### PR TITLE
fix: update documentation url

### PR DESCRIPTION
**Pull request by lexfrei**
old url looks like 404 now

### CODE REVIEW

**Comment by andrewrynhard** [comment]
Thanks @lexfrei!

**Comment by andrewrynhard** [comment]
@lexfrei can you amend the commit as `fix: update documentation url` please? We enforce conventional commits :)

**Comment by andrewrynhard** [comment]
@lexfrei Try this 
```
git commit -s --amend -m 'fix: update documentation url' -m 'old url looks like 404 now'
```

**Comment by lexfrei** [comment]
@andrewrynhard it's not easy to do this on phone :)
Is it done?

**Comment by andrewrynhard** [comment]
@lexfrei It's not :) ... when your in front of a computer, there will be two things you need to do. We require 1 commit to keep the tree linear, and we require conventional commit format so that we can generate our CHANGELOG automatically. So you'll need to rebase and squash everything down to 1 commit that is in conventional commit format.

**Comment by andrewrynhard** [comment]
@lexfrei I know its a bit of a pain, but do you mind amending and squashing down to 1 conventional commit?

**Comment by andrewrynhard** [comment]
See https://github.com/talos-systems/talos/pull/1558.

**Pull request closed without merging**
