### PR TITLE
Aws guide updates for feb

### PR DESCRIPTION
**Pull request by steverfrancis**
# Pull Request

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by steverfrancis** [comment]
Incidentally, I just guessed the port number for the update to
Generating Base Configurations
talosctl gen config talos-k8s-aws-tutorial https://<load balancer IP or DNS>:6443

**Comment by Ulexus** [comment]
Is the reason for this that the `--group-id` has gone away?

**Comment by steverfrancis** [comment]
> Is the reason for this that the `--group-id` option has gone away from the `aws` cli tool?

You only need one of --group-id or --group-name.
And we know the group-name.

(Although, "For security groups in a nondefault VPC, you must specify the security group ID." How often is that a thing?)

**Comment by steverfrancis** [comment]
Going to review some stuff with Spencer

**Pull request closed without merging**
