### PR TITLE
docs: add guide on setting up air-gapped environment with `images`

### LINKED ISSUE #2544: Document airgapped Talos
### Description

We need to add documentation to the airgap install guide that shows how to use the `images` command.

### PR DESCRIPTION
**Pull request by smira**
Fixes #2544

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/talos-systems/talos/2585)

### CODE REVIEW

**Comment by smira** [comment]
https://deploy-preview-2585--talos-dev.netlify.app/docs/v0.7/en/guides/local/air-gapped

**Review by andrewrynhard — DISMISSED** [review]

**Pull request merged**
