### PR TITLE
docs(upgrading-talos): fix typo for stage flag

### PR DESCRIPTION
**Pull request by ammmze**
# Pull Request

## What? (description)

Found typo in the upgrading talos docs. It mentioned `--staged` flag, but it appears the flag is `--stage`.

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

**Comment by smira** [comment]
@ammmze would you mind changing config header to just `docs: fix typo for stage flag` as our conform checks are broken with scopes, and this scope is not valid anyways.

also your commit seems to be missing DCO (`git commit --amend -s`).

and please apply same change to 0.10 docs

thank you!

**Comment by ammmze** [comment]
> @ammmze would you mind changing config header to just `docs: fix typo for stage flag` as our conform checks are broken with scopes, and this scope is not valid anyways.
> 
> also your commit seems to be missing DCO (`git commit --amend -s`).
> 
> and please apply same change to 0.10 docs
> 
> thank you!

👍🏻  Updates pushed

**Comment by smira** [comment]
@ammmze commit body is empty, we require something in the commit body, thanks!

**Comment by smira** [comment]
> @ammmze commit body is empty, we require something in the commit body, thanks!

nvm, you already fixed it

**Review by smira — APPROVED** [review]

**Pull request merged**
