### PR TITLE
chore: bump module dependencies in go.mod

### PR DESCRIPTION
**Pull request by smira**
This covers most of the packages except for those we have to keep on
hold (etcd and grpc because of etcd).

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by rsmitty — APPROVED** [review]

**Comment by rsmitty** [comment]
Is the dhcp change intentional?

**Review by andrewrynhard — APPROVED** [review]

**Comment by smira** [comment]
> Is the dhcp change intentional?

yes, because dhcp package api got slightly changed

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
