### PR TITLE
fix: get rid of data race in encoder and fix concurrent map access

### PR DESCRIPTION
**Pull request by AlekSi**
Cherry-pick https://github.com/talos-systems/talos/pull/3381 for 0.9.

### CODE REVIEW

**Comment by AlekSi** [comment]
@smira PTAL. I probably messed up project and milestones of this and linked PRs / issues

**Comment by smira** [comment]
> @smira PTAL. I probably messed up project and milestones of this and linked PRs / issues

Lgtm!

**Review by smira — APPROVED** [review]

**Review by Unix4ever — APPROVED** [review]

**Comment by smira** [comment]
@AlekSi looks like Drone missed the notification for this PR, would you mind amending your commit to trigger the build once again?

**Review by smira — APPROVED** [review]

**Pull request merged**
